// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1021FZ.Data;

#nullable disable

namespace _1021FZ.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241021092823_Createdblog")]
    partial class Createdblog
    {
        /// <inheritdoc />
        protected  void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("_1021FZ.Models.BlogRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updatedat")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("blogRegistry");
                });

            modelBuilder.Entity("_1021FZ.Models.Blogger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("BlogRegistryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("dateat")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BlogRegistryId");

                    b.ToTable("bloggers");
                });

            modelBuilder.Entity("_1021FZ.Models.Blogger", b =>
                {
                    b.HasOne("_1021FZ.Models.BlogRegistry", null)
                        .WithMany("Blogs")
                        .HasForeignKey("BlogRegistryId");
                });

            modelBuilder.Entity("_1021FZ.Models.BlogRegistry", b =>
                {
                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
